--- 
  components: 
    schemas: 
      Aircraft: 
        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Aircraft/model.yaml#/Aircraft"
  info: 
    description: |
      Aircraft entity contains a description of a generic aircraft with the standard parameters used by the airline industry.

    title: Aircraft
    version: "1.0.0"
  openapi: "3.0.0"
  
  # These paths are merely representative.
  paths: 
    /ngsi-ld/v1/entities: 
      get: 
        description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
        parameters: 
          - 
            in: query
            name: type
            required: true
            schema: 
              enum: 
                - Aircraft
              type: string
        responses: 
          ? "200"
          : 
            content: 
              application/ld+json: 
                examples: 
                  keyvalues: 
                    summary: "Key-Values Pairs"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Aircraft/examples/example.jsonld"
                  normalized: 
                    summary: "Normalized NGSI-LD"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Aircraft/examples/example-normalized.json"
            description: OK
        tags: 
          - ngsi-ld
  tags: 
    - 
  
      description: "NGSI-LD Linked-data Format"
      name: ngsi-ld
  
