--- 
  components: 
    schemas: 
      Flight: 
        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Flight/model.yaml#/Flight"
  info: 
    description: |
      Flight entity contains a description of a generic flight with the standard parameters used by the airline industry. This model is based on specifications published by the main organisms of the industry such us EUROCONTROL, ICAO and IATA.
    
    title: Flight
    version: "1.0.0"
  openapi: "3.0.0"
  
  # These paths are merely representative.
  paths: 
    /ngsi-ld/v1/entities: 
      get: 
        description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
        parameters: 
          - 
            in: query
            name: type
            required: true
            schema: 
              enum: 
                - Flight
              type: string
        responses: 
          ? "200"
          : 
            content: 
              application/ld+json: 
                examples: 
                  keyvalues: 
                    summary: "Key-Values Pairs"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Flight/examples/example.jsonld"
                  normalized: 
                    summary: "Normalized NGSI-LD"
                    value: 
                      - 
                        $ref: "https://smart-data-models.github.io/incubated/Aeronautics/Flight/examples/example-normalized.json"
            description: OK
        tags: 
          - ngsi-ld
  tags: 
    - 
  
      description: "NGSI-LD Linked-data Format"
      name: ngsi-ld
  
