name: Validate schemas

on:
  push:

jobs:
  create-test-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: list-schema-files
        run: |
          echo "::set-output name=matrix::$(jq -ncR '[inputs]' <<< $(find . -print | grep -i 'schema.json'))"

    outputs:
      matrix: ${{ steps.list-schema-files.outputs.matrix }}

  validate-schemas:
    needs: create-test-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schema-file: ${{ fromJson(needs.create-test-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - id: get-folder
        run: |
          echo "::set-output name=folder::$(basename $(dirname ${{ matrix.schema-file }}))"

      - uses:  wistefan/validate-data-model@master
        id: validate
        name: Validate
        continue-on-error: true
        with:
          schema-file: ${{ matrix.schema-file }}
          failure-file: ${{ steps.get-folder.outputs.folder }}-failure.json
          annotations-file: ${{ steps.get-folder.outputs.folder }}-annotation.json

      - name: Upload failure report
        if: steps.validate.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get-folder.outputs.folder }}-failure.json
          path: ${{ steps.get-folder.outputs.folder }}-failure.json

      - name: Annotate
        if: steps.validate.outcome == 'failure'
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          input: ${{ steps.get-folder.outputs.folder }}-annotation.json